name: Trading-System

on:
  push:
    branches:
      - Version-2

jobs:
  build:
    name:  Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@Version-2
      - uses: actions/setup-java@Version-2
      - name: Set up JDK 8
        with:
          java-version: '8'
      - name: Run Tests
        run: ./gradlew -b ci.gradle package
