name: test


on: [push]
jobs: 
  build: 
    runs-on: 
      - ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Set up JDK 8"
        uses: actions/setup-java@v2
        with: 
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: "8"
      - 
        name: "Cache Maven packages"
        uses: actions/cache@v2
        with: 
          key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
          path: ~/.m2
          restore-keys: "${{ runner.os }}-m2"
      - 
        name: "Run tests with Maven"
        run: "mvn -B test --file ./version_1/Trading-System/pom.xml"
